#ifndef LANG_TR_H
#define LANG_TR_H
#include <Arduino.h>
#include "lang.h"

const LanguagePack LANG_TR = {
    "tr",
    "İÇ MEKAN SICAKLIĞI",
    "İÇ MEKAN NEMİ",
    {"PAZ", "PZT", "SAL", "ÇAR", "PER", "CUM", "CMT"},
    {"OCA", "ŞUB", "MAR", "NİS", "MAY", "HAZ", "TEM", "AĞU", "EYL", "EKİ", "KAS", "ARA"},
    {"GÜNEŞ", "AY"},
    {"YENİ AY", "HİLAL", "İLK DÖRDÜN", "ŞİŞKİN AY", "DOLUNAY", "ŞİŞKİN AY", "SON DÖRDÜN", "HİLAL"},
    {"K", "KD", "D", "GD", "G", "GB", "B", "KB"},
    {"KUZEY", "KUZEYDOĞU", "DOĞU", "GÜNEYDOĞU", "GÜNEY", "GÜNEYBATI", "BATI", "KUZEYBATI"},
    {"İYİ", "İDARE EDER", "ORTA", "KÖTÜ", "ÇOK KÖTÜ"},
    {"DÜŞÜK", "İDARE EDER", "YÜKSEK", "ÇOK YÜKSEK", "AŞIRI YÜKSEK"},
    {"Saat güncelleniyor...", "OWM güncelleniyor...", "Astronomi güncelleniyor...", "Open-Meteo güncelleniyor...", "Bitti..."},
    "GECE MODU BAŞLIYOR",
    "GECE MODU BİTTİ",
    "OTA BAŞLIYOR",
    "OTA YÜKLENİYOR",
    "OTA BİTTİ",
    "OTA HATA",
    "SONRAKİ GÜNCELLEME",
    "ESP8266 Hava Durumu İstasyonu",
    "Cihaz Ayarları",
    "Güvenlik Ayarları",
    "OpenWeatherMap API Anahtarı",
    "API anahtarınızı girin",
    "Göster",
    "OpenCage API Anahtarı",
    "Şehir Adı",
    "Örnek: İstanbul",
    "Ülke Adı",
    "Örnek: Türkiye",
    "Şehirden Konum/Zaman Dilimi Bul",
    "Enlem",
    "Örnek: 41.17",
    "Boylam",
    "Örnek: 28.86",
    "Zaman Dilimi",
    "Birim Seçiniz",
    "Metrik",
    "İngiliz",
    "Güncelleme Sıklığı (Dakika)",
    "Kaydet",
    "Anasayfa",
    "Lütfen şehir, ülke ve OpenCage API anahtarını girin.",
    "Konum bulunamadı.",
    "API isteği başarısız.",
    "Hakkında",
    "Şifre",
    "Kullanıcı Adı",
    "Kullanıcı adı giriniz",
    "Şifre giriniz",
    "Varsayılan Ayarlar",
    "Varsayılan ayarlarına dönüldü. Cihaz yeniden başlatılıyor...",
    "Varsayılan ayarlarlara dön",
    "Cihaz varsayılan ayarlarına dönecek. Devam edilsin mi?",
    "Gizle",
    "OTA Güncellemesi",
    "Açılma Zamanı",
    "Kapanma Zamanı",
    "Güvenlik bilgileri başarıyla değiştirildi.",
    "Cihaz ayarları başarıyla kaydedildi. Ana sayfaya yönlediriliyor...",
    "Buradan",
    "alınız",
    "Ekran yönünü çevir",
    "Kaydediliyor...",
    "Ekran Ayarları",
    "Ekran ayarları başarıyla kaydedildi. Ana sayfaya yönlediriliyor...",
    "API Anahtar Ayarları",
    "API Anahtarları başarıyla kaydedildi. Ana sayfaya yönlediriliyor...",
    "Zaman dilimi bulunamadı",
    "Zaman dilimleri alınamadı: ",
    "Zaman dilimleri yüklenemedi.",
    "Ekran Parlaklığı",
    "Saat Formatı",
    "Verileri Güncelle",
    "24 Saat",
    "12 Saat",
    "Ay Gösterim Formatı",
    "Sayı Olarak (Gün/Ay)",
    "Yazı Olarak",
    "Lütfen açılma/kapanma saatini 24 saat formatında giriniz.",
    "Haritada Göster",
    "Güvenlik ayarları başarıyla kaydedildi. Ana sayfaya yönlediriliyor...",
    "HAVA DURUMU İST",
    "Sinyal Gücü (RSSI):",
    "Bu URL'yi kullanın:",
    "readyForUpdate true olarak ayarlandı",
    "Ekran Açıldı:",
    "Ekran Kapatıldı:",
    "Ekranı açma zamanı:",
    "Ekranı kapatma zamanı:",
    "Yapılandırma moduna girildi",
    "Lütfen AP'ye bağlanın",
    "WiFi bağlantısı kurulumu için",
    "Cihaz Ayarları Güncellendi:",
    "Güvenlik Ayarları Güncellendi:",
    "Bu isimde bir dosya yok",
    "OTA güncellemesi başladı!",
    "OTA İlerleme Durumu",
    "Şu an",
    "Final",
    "OTA güncellemesi başarıyla tamamlandı!",
    "OTA güncellemesi sırasında bir hata oluştu!",
    "API Anahtarları Güncellendi:",
    "NTP zamanı bekleniyor...",
    "Zaman senkronize edildi.",
    "Ekran Ayarları Güncellendi:",
    "Dosya açma başarısız!",
    "Ayarlar kaydediliyor...",
    "Sistem Dili"
};

#endif