#ifndef LANG_EN_H
#define LANG_EN_H
#include <Arduino.h>
#include "lang.h"

const LanguagePack LANG_EN = {
    "en",
    "INDOOR TEMPERATURE",
    "INDOOR HUMIDITY",
    {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"},
    {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"},
    {"SUN", "MOON"},
    {"NEW MOON", "WAXING CRESCENT", "FIRST QUARTER", "WAXING GIBBOUS", "FULL MOON", "WANING GIBBOUS", "THIRD QUARTER", "WANING CRESCENT"},
    {"N", "NE", "E", "SE", "S", "SW", "W", "NW"},
    {"NORTH", "NORTHEAST", "EAST", "SOUTHEAST", "SOUTH", "SOUTHWEST", "WEST", "NORTHWEST"},
    {"GOOD", "MODERATE", "FAIR", "POOR", "VERY POOR"},
    {"GOOD", "MODERATE", "HIGH", "VERY HIGH", "EXTREME"},
    {"Updating time...", "Updating OWM...", "Updating astronomy...", "Updating Open-Meteo...", "Done..."},
    "NIGHT MODE IS STARTING",
    "NIGHT MODE IS FINISHED",
    "OTA IS STARTING",
    "OTA IS UPLOADING",
    "OTA IS FINISHED",
    "OTA ERROR",
    "NEXT UPDATE",
    "ESP8266 Weather Station",
    "Device Settings",
    "Security Settings",
    "OpenWeatherMap API Key",
    "Enter your API key",
    "Show",
    "OpenCage API Key",
    "City Name",
    "Example: Istanbul",
    "Country Name",
    "Example: Turkey",
    "Find Location/Timezone from City",
    "Latitude",
    "Example: 41.17",
    "Longitude",
    "Example: 28.86",
    "Time Zone",
    "Select Unit",
    "Metric",
    "Imperial",
    "Update Interval (Minutes)",
    "Save",
    "Homepage",
    "Please enter city, country and OpenCage API key.",
    "Location not found.",
    "API request failed.",
    "About",
    "Password",
    "Username",
    "Enter username",
    "Enter password",
    "Default Settings",
    "Restore to default settings. The device is restarting...",
    "Restore to Default Settings",
    "The device will be reset to default settings. Continue?",
    "Hide",
    "OTA Update",
    "Turn On Time",
    "Turn Off Time",
    "Security information successfully changed.",
    "Device settings saved successfully. Redirecting to homepage...",
    "Get from",
    "here",
    "Flip display orientation",
    "Saving...",
    "Display Settings",
    "Display settings saved successfully. Redirecting to homepage...",
    "API Key Settings",
    "API keys saved successfully. Redirecting to homepage...",
    "Time zone not found",
    "Time zones could not be retrieved:",
    "Time zones could not be loaded.",
    "Display Contrast",
    "Time Format",
    "Update Data",
    "24-hour",
    "12-hour",
    "Month Display Format",
    "As Number (Day/Month)",
    "As Name",
    "Please enter the on/off time in 24-hour format.",
    "Show on Map",
    "Security settings saved successfully. Redirecting to homepage...",
    "WEATHER STATION",
    "Signal Strength (RSSI):",
    "Use this URL:",
    "Setting readyForUpdate to true",
    "Display was turned on:",
    "Display was turned off:",
    "Time to turn display on:",
    "Time to turn display off:",
    "Entered config mode",
    "Please connect to AP",
    "To setup WiFi connection",
    "Device Settings Updated:",
    "Security Settings Updated:",
    "There is no file with that name.",
    "OTA update started!",
    "OTA Progress",
    "Current",
    "Final",
    "OTA update finished successfully!",
    "There was an error during OTA update!",
    "API Keys Updated:",
    "Waiting for NTP time...",
    "Time synchronized.",
    "Display Settings Updated:",
    "File open failed!",
    "Saving settings now...",
    "System Language"
};

#endif